# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/image_analyzer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/image_analyzer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto/image_analyzer.proto\x12\x0eimage_analyzer\"$\n\x0e\x41nalyzeRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"H\n\x0f\x41nalyzeResponse\x12\x14\n\x0cproduct_name\x18\x01 \x01(\t\x12\x0e\n\x06vector\x18\x02 \x03(\x02\x12\x0f\n\x07success\x18\x03 \x01(\x08\x32`\n\rImageAnalyzer\x12O\n\x0c\x41nalyzeImage\x12\x1e.image_analyzer.AnalyzeRequest\x1a\x1f.image_analyzer.AnalyzeResponseB\x17Z\x15\x64\x65stinyface/gen/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.image_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\025destinyface/gen/proto'
  _globals['_ANALYZEREQUEST']._serialized_start=46
  _globals['_ANALYZEREQUEST']._serialized_end=82
  _globals['_ANALYZERESPONSE']._serialized_start=84
  _globals['_ANALYZERESPONSE']._serialized_end=156
  _globals['_IMAGEANALYZER']._serialized_start=158
  _globals['_IMAGEANALYZER']._serialized_end=254
# @@protoc_insertion_point(module_scope)
